version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.7.0
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn test

workflows:
  version: 2
  build_test_deploy:
      jobs:
        - test

